### ISSUE TITLE
Integrate PR for bold fonts?

### ISSUE THREAD

**Issue by bfulop** [akiyosi/gonvim#10]
Hello,

I was testing out gonvim, it looks really great and fast! 👍  One thing I was missing was the support for __bold__ fonts.

It seems like [this pull request](https://github.com/dzhou121/gonvim/pull/87) on dzhou121/gonvim is aimed to fix that.

Do you think it would be possible to somehow integrate this into your branch?

EDIT: the original title was bold and italic fonts, sorry for the false alert, of course italic fonts are supported by Gonvim!

**Comment by akiyosi** [comment]
gonvim supports bold fonts.
[The pull request](https://github.com/dzhou121/gonvim/pull/87) has already been merged.

**Comment by bfulop** [comment]
Ah sorry about this then! ☺️

I'll check with another font then! In fact compared to what I see in iTerm-nvim, the fonts in the Gonvim look bolder, ie the code seems to be displayed in bold and bold-italic.

**Comment by bfulop** [comment]
Hello, 

I've found why texts looked bold in Gonvim compared to iTerm: the _Use font smoothing when available_ option was turned of in the system preferences :

![font_smoothing](https://user-images.githubusercontent.com/1718128/48427250-a6737680-e768-11e8-9fa2-51ecdddd3567.jpg)

If I turn this off, fonts will be displayed in their original (lighter) weights.

But this shows that Gonvim displays all texts at the same, normal weight:

![font-bold](https://user-images.githubusercontent.com/1718128/48427381-e33f6d80-e768-11e8-9770-fe70d62fdabb.jpg)

Is there maybe a setting that I forgot that would enable Gonvim use bolds fonts? 

Do you think it would be better to raise this issue on the original pull request?

I really love the mix of normal, bold, italic text for displaying code, it makes the syntax more readable.

**Comment by akiyosi** [comment]
Hi,
I think it is okay to discuss this font probrem with this issue.

What is your font-family and colorscheme?
Gonvim displays bold-font if bold is enabled in colorscheme.
I confirmed the _Use font smoothing when available_, but the bold font was valid for either setting.
Here is my screenshot. it is "FantasqueSansMono Nerd Font Mono" and [vim-github-colorscheme
](https://github.com/endel/vim-github-colorscheme)


<img width="1127" alt="ss-2018-11-14 14 38 57" src="https://user-images.githubusercontent.com/8478977/48462502-c6b03d80-e81b-11e8-9b8b-888e4d695801.png">

**Comment by bfulop** [comment]
Thanks, that's definitely good news then! I will try with your setup then. 

What lead me to think that bold fonts were broken was the fact that other Neovim GUIs (VV) and iTerm were showing the bold fonts with the same font and same scheme. I'm using the `Hack` font with the [inkstained](https://github.com/yuttie/inkstained-vim) colors, but also tried with Gruvbox. 

By the way, I really love how Gonvim adapts to the active colorscheme! I haven't seen this with the original Gonvim repo. It's really very nicely done!

**Comment by bfulop** [comment]
I tried your setup, but unfortunately sill cannot get the bold fonts displayed. I [downloaded FantasqueSansMono-normal.zip](https://github.com/belluzj/fantasque-sans/releases/tag/v1.7.2) and the GitHub theme. 

My `ginit.vim` file has this:

```
GuiFont Fantasque Sans Mono:h13
GuiLinespace 7
```

And `.gonvim` this:

```
...
fontFamily = "Fantasque Sans Mono"
fontsize = 13
linespace = 7
# Editor cursor blink
cursorBlink = false
# Disable IME in Normal mode
disableIMEinNormal = true
...
```


<img width="600" alt="fantasque-github" src="https://user-images.githubusercontent.com/1718128/48470081-c77faa00-e7f0-11e8-806b-d1467c18f0c3.png">

Could it be that I'm still missing some setting somewhere? (I'm using the latest version of Gonvim available from the releases page)

**Comment by bfulop** [comment]
I also tried with just a minimal `init.vim` like so, bit did not solve it either unfortunately:

```
set nocompatible
set nonumber
set ignorecase
set smartcase
set expandtab
set inccommand=nosplit
filetype plugin on

set hidden
set cmdheight=1
set noshowmode

call plug#begin('~/config/.nvim/plugged')
  Plug 'endel/vim-github-colorscheme'
  Plug 'equalsraf/neovim-gui-shim'
  Plug 'akiyosi/gonvim-fuzzy'
call plug#end()

set background=light
set termguicolors
colorscheme github


```

**Comment by bfulop** [comment]
Yes, I'm on Mojave, and unfortunately did not test bold fonts with Gonvim on High Sierra before upgrading!

So I guess the best is to wait until the Qt dependency used by Gonvim is updated? Of course it's not mission critical for me, just something that would be nice to have eventually.

**Comment by akiyosi** [comment]
There is no other idea of the bold font probrem, so I think we have to wait for Qt 5.12.
But it was released soon;
https://wiki.qt.io/Qt_5.12_Release

If [therecipe/qt](https://github.com/therecipe/qt) supports Qt 5.12 then gonvim will also follow.

**Comment by bfulop** [comment]
That's great, thanks for the heads-up! Let's wait for the Qt update then, it really looks like it will solve it.

**Comment by bfulop** [comment]
Hello,

Just wanted to report that last week I was trying out the Iosevka font family with Gonvim and with this font the font weights are displayed correctly (but not italic...)! I don't really understand why Iosevka has better compatibility but anyway it's a great  looking font so don't mind sticking with it.

<img width="474" alt="screenshot 2018-12-10 at 15 53 27" src="https://user-images.githubusercontent.com/1718128/49740368-494de080-fc94-11e8-8aeb-429308dd3977.png">

**Comment by bfulop** [comment]
Hello, 

I can confirm that the [latest release](
https://github.com/akiyosi/gonvim/releases/download/v0.3.2/Gonvim-0.3.2-macos.tar.gz) for MacOS displays correctly all font weights!

Thanks for providing this release, it works great on my machine! I close this issue as it seems to be resolved now.
