### ISSUE TITLE
Ignore files in GonvimFuzzyFiles

### ISSUE THREAD

**Issue by bfulop** [akiyosi/gonvim#11]
Hello, 

This is related to the `akiyosi/gonvim-fuzzy` repo, but I couldn't open an issue there.

I was wondering, is there a way to ignore some directories or files (using `.gitignore` for example) reported by `GonvimFuzzyFiles` ?

**Comment by akiyosi** [comment]
Hi,
Sorry I was wrong. `GonvimFuzzzyFiles` does not use `ag`.

I fixed this problem and updated the release.
Please try to confirm.

**Comment by bfulop** [comment]
Working perfectly now, thanks for the quick fix!
