### ISSUE TITLE
Disabling Vim statusline not working?

### ISSUE THREAD

**Issue by bfulop** [akiyosi/gonvim#13]
Hello,

I would like to get rid of–if possible–the unused space at the bottom of the editor (built in Vim status line and white space):

![statusline](https://user-images.githubusercontent.com/1718128/48473108-0fee9600-e7f8-11e8-80ba-17326e0dabfa.jpg)

I was following the [Modern UI](
https://github.com/akiyosi/gonvim/wiki/Configurations#modern-ui) instructions and set

```init.vim
let g:gonvim_draw_statusline = 0
```

but, the Vim statusline is still visible.

The 

```init.vim
let g:gonvim_draw_tabline = 0
```

does seem to work however.

**Comment by akiyosi** [comment]
Hi,
To turn off statusbar of neovim, you need to set the following in `init.vim`; 

```
set laststatus=0
```

**Comment by bfulop** [comment]
Thanks for the quick reply, it works!
