### ISSUE TITLE
Request: Set `g:gonvim_running` earlier in load

### ISSUE THREAD

**Issue by wbthomason** [akiyosi/gonvim#14]
Would it be possible to set `g:gonvim_running` earlier in the load sequence? I have several plugins (airline, etc.) I would like to disable if Gonvim is running instead of terminal Neovim, but this currently doesn't work because the `g:gonvim_running` variable isn't set until after `init.vim` is sourced.

Alternately, is there another recommended way to conditionally disable plugins if in Gonvim instead of TUI Neovim?

**Comment by Shougo** [comment]
I think the feature cannot implement.
Because, neovim is initialized before GUI initialize.
gonvim may set environment variable for check.

**Comment by wbthomason** [comment]
Ah, I did not realize that the initialization order was Neovim -> GUI. That makes sense, though. An environment variable would also work; perhaps `GONVIM_RUNNING`? As long as it's set only in the environment of the Neovim process, that should behave nicely with respect to crashes, etc.

**Comment by akiyosi** [comment]
Hi, 
As Shougo says init.vim is processed before the GUI.
One solution is to use `ginit.vim` which is loaded after `g:gonvim_running` is set.


``` 
" ginit.vim
if g:gonvim_running == 1
  set laststatus=0
endif
```

**Comment by akiyosi** [comment]
Hi, 
I improved to load `g:gonvim_running` earlier than `init.vim` on [v0.3.1](https://github.com/akiyosi/gonvim/releases/tag/v0.3.1). try it.

**Comment by wbthomason** [comment]
Thank you!
