### ISSUE TITLE
White text in Gonvim UI with 3.1

### ISSUE THREAD

**Issue by bfulop** [akiyosi/gonvim#21]
Hello,

I just updated to version 3.1 that was released today. I noticed that all UI texts are white now. This is especially difficult with the commands palette, where I can't see the text I'm typing. 

Is there maybe a new setting that was and added and that I should change to tweak the text colour?

<img width="700" alt="screenshot 2018-12-05 at 15 15 14" src="https://user-images.githubusercontent.com/1718128/49519352-1628dd00-f8a1-11e8-94c8-e28a17b0bfc0.png">

**Comment by bfulop** [comment]
On the other hand, if I use Gonvim 3.0, I don't have this problem, but I get this error:

```
E492: Not an editor command: GonvimFuzzyFiles
```

I need to source `init.vim`, and after that I can use these Gonvim commands (`GonvimFuzzyFiles` etc). Again, this only on version 3.0.

**Comment by akiyosi** [comment]
The first problem seems to be a bug and I will fix it tommorow. sorry😅
The second problem is probably due to the addition of `if exists ('g: gonvim_running')` processing. 
https://github.com/akiyosi/gonvim-fuzzy/commit/0c7e8d8b6cdb76da0b7c2e9ed4beeade4f44ec56#diff-d91cb480ef681677f4c87a477733aea6

As a workaround, please write the following in `ginitvim` of `setting.toml`.

``` 
[Editor]
ginitvim = '''
  command! -nargs=? GonvimFuzzyFiles   call gonvim_fuzzy#files(<q-args>, <bang>0)
  command! -nargs=? GonvimFuzzyBLines  call gonvim_fuzzy#buffer_lines(<q-args>, <bang>0)
  command! -nargs=? GonvimFuzzyAg      call gonvim_fuzzy#ag(<q-args>, <bang>0)
  command! -nargs=? GonvimFuzzyBuffers call gonvim_fuzzy#buffers(<q-args>, <bang>0)
'''
```

**Comment by bfulop** [comment]
Great, and thank you so much for the quick reply !

**Comment by akiyosi** [comment]
I Updated fixed release.

**Comment by bfulop** [comment]
Thank you for fixing it so fast! I can confirm that it's working perfectly now!
