### ISSUE TITLE
Supports Qt5.12.

### ISSUE THREAD

**Issue by akiyosi** [akiyosi/gonvim#23]
therecipe/qt now supports Qt5.12.
Gonvim is ready for Qt5.12.

**Comment by bfulop** [comment]
That's great news! Maybe it'll resolve #10 as well!

**Comment by akiyosi** [comment]
This issue will be closed due to the following reasons.
* There was no code modification for Qt 5.12 support.
* There are circumstances, only macOS support for the time being.
