### ISSUE TITLE
Required plugins

### ISSUE THREAD

**Issue by dobegor** [akiyosi/gonvim#3]
Could you please mention which plugins are required?
Because out-of-the box experience (only neovim installed) is pretty ugly:
![img](https://i.imgur.com/v8oBpHJ.png)

**Comment by akiyosi** [comment]
Hi
The plugin I recommend is below. If you feel that setting is troublesome, it is recommended to clone the setting of those who publish init.vim (vimrc) as repository to github.

* Manages the plugins
[Shougo/dein.vim](https://github.com/Shougo/dein.vim)

* Color scheme
1. [andreypopp/vim-colors-plain](https://github.com/andreypopp/vim-colors-plain) (I used the top image of this repositry)
1. [joshdick/onedark.vim](https://github.com/joshdick/onedark.vim) (atom like dark / light color scheme)

* lint
[w0rp/ale](https://github.com/w0rp/ale)

* Compression
[Shougo/deoplete.nvim](https://github.com/Shougo/deoplete.nvim)

**Comment by dobegor** [comment]
Thank you for the tips!
And what about git status info with git branch icon? Or is it a built-in feature of gonvim?

**Comment by akiyosi** [comment]
The git icon is constant, not the status in particular. 
The label to the right of the git icon indicates the state of git in the repository.

**Comment by dobegor** [comment]
Yep, I know what they mean, I just asked what plugin I need to install for this icons to work. Currently I don't have any git info with gonvim.

**Comment by akiyosi** [comment]
The git icon display of gonvim is a built-in feature, so you do not need any additional plug-in. It is displayed for files under the directory associated with the git repository.
