### ISSUE TITLE
Ctrl+N does not allow looping through all autocomplete suggestions

### ISSUE THREAD

**Issue by jaapz** [akiyosi/gonvim#32]
In neovim (in the terminal) I am able to use Ctrl+N to scroll through all suggested autocompletes. In Gonvim, when pressing Ctrl+N, the first suggested item is selected which then clears all other autocomplete suggestions from the list. When I use the "down" arrow to select autocomplete suggestions, I am able to scroll through all suggestions without them dissappearing.

**Comment by akiyosi** [comment]
Thank you for the report.
It is probably a bug in coordinates of autocomplete suggestions UI drawing with Gonvim. I will fix it in v0.3.3.
