### ISSUE TITLE
Minimum width

### ISSUE THREAD

**Issue by b-fuze** [akiyosi/gonvim#35]
I would like to set the `Width` in `setting.toml` to smaller than `800`px
![image](https://user-images.githubusercontent.com/10504957/51809192-fc39c400-226b-11e9-9bdf-4eb482af7314.png)
I assume from `>=` a minimum is hardcoded, can that be changed?

**Comment by bfulop** [comment]
Same here, for a long time I wanted to raise the same issue.

I'm oftentimes working on a 12" laptop, and running Gonvim without the sidebar, gutter, line numbers, plus using a very narrow font (Iosevka). With this setup I could easily reduce the window width to `400px`.

**Comment by akiyosi** [comment]
Hi,
Thanks for the suggestion. I will consider about that in the next version.
The reason why the minimum size is set to 800 is because the application crashes when drawing a GUI with a small size currently.😓

**Comment by b-fuze** [comment]
Some division by zero issue probably? I should try to debug it...

**Comment by akiyosi** [comment]
I changed the minimum value in v0.3.4. Try it.
