### ISSUE TITLE
Odd font render

### ISSUE THREAD

**Issue by theFool32** [akiyosi/gonvim#36]
![default](https://user-images.githubusercontent.com/3063690/52909876-f31ba000-32c9-11e9-8f36-152fcb39c201.png)

As the picture shown, font render in gonvim is odd.

ArchLinux, nvim v0.3.4, gonvim 0.3.3.
`setting.toml` is same as the one in wiki.
Empty nvim configure give same result.

Any solutions?
Thanks.

**Comment by akiyosi** [comment]
Hi,
Are you using the setting `FontFamily = "Monospace"` in `setting.toml`?
In that case, the font `Monospace` may not be installed on the system or its name may be different. Please specify the font-family that exists in the system.

**Comment by theFool32** [comment]
Thanks, @akiyosi 
I am using `FontFamily = "Monospace"` as you said. 
What should I set if I want to use `Source Code Pro` font. Simply set `FontFamily = "Source Code Pro"` not works.

**Comment by akiyosi** [comment]
Oh, I forgot to mention one.
Are you also setting the following?

```
GinitVim = '''
  	set guifont=FuraCode\ Nerd\ Font\ Mono:h14
'''
```

In that case, this vimsctipt is loaded after Gonvim startup.
Please delete this and retry it.

**Comment by theFool32** [comment]
I tried empty `setting.toml` and the problem remains.

**Comment by akiyosi** [comment]
If `setting.toml` does not exist, Gonvim sets the `Monospace` as the default font-family in the ArchLinux. If Monospace does not exist on your system, Gonvim does not know which font-family is used
Please try specifying the font-family that exists on the system in the `setting.toml`.

**Comment by theFool32** [comment]
The problem is gone after running an old version and switch back to the newest one with empty setting.toml.
