### ISSUE TITLE
can commands display in command line?

### ISSUE THREAD

**Issue by epheien** [akiyosi/gonvim#38]
I just need experiment as run in terminal, so it's better display typing command in command line.

**Comment by akiyosi** [comment]
Hi,
I do not understand your issue well.
Will you explain in a little more detail?

**Comment by Shougo** [comment]
I think the issue is to disable current external command line behavior in gonvim.

**Comment by epheien** [comment]
> I think the issue is to disable current external command line behavior in gonvim.

Yes, the command line behavior like gvim.
Give a option to control this behavior is better.

**Comment by akiyosi** [comment]
Thanks for the explanation. understood.
I will add that setting item in the next version.

**Comment by epheien** [comment]
> Thanks for the explanation. understood.
> I will add that setting item in the next version.

Thanks. After fixing this issue, gonvim is the best gvim of nvim on macOS!

**Comment by akiyosi** [comment]
You get the expected behavior by setting `ExtCmdline = false` in the setting.toml with Gonvim 0.3.4.
