### ISSUE TITLE
QT error while trying to run the project under Ubuntu

### ISSUE THREAD

**Issue by anchnk** [akiyosi/gonvim#40]
I want to give a try to gonvim but I can't get it to run.

I downloaded the release **0.3.3**, extracted the archive and run `./gonvim` in my terminal but I got the following error:

> ./gonvim: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.11' not found (required by ./gonvim)

System informations:

* OS: Ubuntu 18.04
* Kernel: 4.15.0-46-generic

Is installing https://github.com/therecipe/qt a requirement to get the application to run ?

**Comment by akiyosi** [comment]
Hi,

Ummm, the library found under the `Gonvim-0.3.3-linux/lib/`.
Could you avoid errors by passing a path, setting LD_LIBRARY_PATH, or creating SYMLINK?

**Comment by anchnk** [comment]
I tried the following

› `export LD_LIBRARY_PATH=./lib && ./gonvim`

And got this error:

> qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**Comment by akiyosi** [comment]
Try the following 🙂

```
apt-get install libqt5x11extras5
```

**Comment by anchnk** [comment]
Thank you very much for the support and the suggestion.

It happens that `libqt5x11extras5` is already installed on my system.

> `libqt5x11extras5 is already the newest version (5.9.5-0ubuntu1).`

**Comment by akiyosi** [comment]
Are you execure `/path/to/Gonvim-0.3.3-linux/gonvim` ?
Try `/path/to/Gonvim-0.3.3-linux/gonvim.sh`

**Comment by anchnk** [comment]
Oh yeah it works now !
Thank you very much :)
