### ISSUE TITLE
Extra pixels before the line number

### ISSUE THREAD

**Issue by Mariappan** [akiyosi/gonvim#44]
Hi
![Screenshot 2019-04-01 at 5 08 45 PM](https://user-images.githubusercontent.com/947300/55324863-f2695280-54a0-11e9-9cb7-6c9faac6d243.png)

A few extra pixels before the line numbers might be visually pleasing 😄

**Comment by akiyosi** [comment]
Hi :smile:

I agree too.
0.4.0 currently under development improves this point.
This is a screenshot under development.
<img width="945" alt="スクリーンショット 2019-04-01 21 25 38" src="https://user-images.githubusercontent.com/8478977/55327380-f1e2b300-54c4-11e9-827a-79adb59524c2.png">

**Comment by Mariappan** [comment]
Great !! Closing this issue then.
Thanks 👍
