### ISSUE TITLE
Default value for 'editor.Transparent'.

### ISSUE THREAD

**Issue by befedo** [akiyosi/gonvim#46]
I’ve just tested the transparent feature and it works like a charm. The only thing I stumbled across is that there is no default value for 'editor.Transparent'.

When the user doesn’t define it in 'settings.toml' the editor window becomes totally transparent.

By the way, nice work and thumbs up ... 👍🏻

**Comment by b-fuze** [comment]
@befedo What's this transparent feature you speak of?

**Comment by befedo** [comment]
@b-fuze It’s the https://github.com/akiyosi/gonvim/tree/feature/transparent?files=1 branch.

**Comment by akiyosi** [comment]
Hi, thank you for your test. 😃 

> The only thing I stumbled across is that there is no default value for 'editor.Transparent'.

Yes, the default value has not been set yet. 
It will probably merge at 0.4.0, so I will add it at that time.

**Comment by befedo** [comment]
Thanks for your response and your time to pushing gonvim forward.

Closing this as it’s an the track ...
