### ISSUE TITLE
Bug: Hangs on some map execution

### ISSUE THREAD

**Issue by noonehereplzgo** [akiyosi/gonvim#48]
When running a some of my maps, the whole editor freezes without leaving any usuful information.

How to reproduce:
```
gonvim 
```

```
:map <space>d :make<cr>
```

then press `<space>d`, the whole editor freezes.

**Comment by akiyosi** [comment]
Hi 😃 
Thank you for reporting the issue.
I have identified the cause of this problem and will release a fix soon.

**Comment by noonehereplzgo** [comment]
The fix solved the issue!

Reporting bugs is the least I can do
Thank you very much!
