### ISSUE TITLE
Help wanted to configure gonvim

### ISSUE THREAD

**Issue by jerrywang1981** [akiyosi/gonvim#49]
MacOS Mojave

* How to run from command like, like other text editor, e.g. VS code 
```
code .
```
to open current folder

* How does the workspace work, I have plugin vim-workspace installed, it looked like it didn't  work, and gonvim took the control of workspace/session, how to disable it.

* the key mapping, e.g I map Option Key + 1 to open Defx, but It didn't work, for now I have to map to <leader><leader>1 

my [gonvim configuration](https://github.com/jerrywang1981/dotfiles/blob/master/gonvim/.gonvim/setting.toml)

Thanks a lot.

**Comment by akiyosi** [comment]
Hi 😄 
> How to run from command like, like other text editor, e.g. VS code `code .`

Currently, gonvim has no command line option to specify the current directory.
I will consider adding options in the future.

> How does the workspace work

Currently, gonvim's workspace/session can not be disabled.

> the key mapping, e.g I map Option Key + 1 to open Defx

Umm, I confirmed that the key inputted `Option(Alt) + 1` is `<A-¡>` in my environment, so I trying to map `nnoremap <A-¡> :Defx<CR>` but can't work. 
If you want to create a shortcut with a combination of meta keys and numbers, you can use the `command` key like the following.

```
nnoremap <D-1> :Defx<CR>
```

**Comment by jerrywang1981** [comment]
I got it, thank you
