### ISSUE TITLE
Build instructions not working

### ISSUE THREAD

**Issue by Anrock** [akiyosi/gonvim#53]
Following instructions from https://github.com/akiyosi/gonvim/wiki/Development
After `go get -d github.com/akiyosi/gonvim/editor/` and `cd $GOPATH/src/github.com/akiyosi/gonvim/cmd/gonvim` executing `qtmoc` does nothing.

According to to `qtmoc --help` it expects some header file as argument, if none provided it reads from STDIN.

I've looked around and there is nothing that looks like header file and i can't provide anything meaningful via STDIN.

**Comment by Anrock** [comment]
@akiyosi qtmoc does nothing. As i said - it requires a path to a header file as argument or some input to STDIN. Instruction says just launch it without any arguments so it waits indefinitely for input and does nothing.

**Comment by Anrock** [comment]
Just in case i'm missing something. This is the contents of `~/go/src/github.com/akiyosi/gonvim`.
```
.
├── cmd
│   └── gonvim
│       ├── darwin
│       │   └── Contents
│       │       ├── Info.plist
│       │       └── Resources
│       │           └── gonvim.icns
│       ├── gonvim.desktop
│       ├── gonvim.go
│       ├── gonvim.ico
│       ├── icon.rc
│       └── icon_windows.syso
├── editor
│   ├── activity.go
│   ├── cmdline.go
│   ├── config.go
│   ├── cursor.go
│   ├── deinGui.go
│   ├── editor.go
│   ├── filelist.go
│   ├── finder.go
│   ├── font.go
│   ├── locpopup.go
│   ├── markdown.go
│   ├── message.go
│   ├── miniMap.go
│   ├── notification.go
│   ├── palette.go
│   ├── popupmenu.go
│   ├── rgba.go
│   ├── screen.go
│   ├── scrollBar.go
│   ├── signature.go
│   ├── statusline.go
│   ├── svg.go
│   ├── tabline.go
│   └── workspace.go
├── fuzzy
│   └── fuzzy.go
├── gonvim.go
├── LICENSE
├── README.md
├── tree
└── util
    ├── util.go
    ├── utils.go
    └── util_win.go

8 directories, 39 files
```

**Comment by befedo** [comment]
Hi there,

I can't confirm that, it's working under Arch Linux and my build looks something like this:
```bash
#!/usr/bin/env bash

export QT_API=5.12.0
export QT_PKG_CONFIG=true
export QT_QPA_PLATFORM=wayland

sudo pacman -S $(pacman -Ssq ^qt5-.*)

go get -u github.com/therecipe/qt/cmd/...

qtsetup

go get -d github.com/akiyosi/gonvim/editor/

cd ${HOME}/go/src/github.com/akiyosi/gonvim/cmd/gonvim/

qtmoc
qtdeploy build desktop
```
Maybe this helps somebody ...

**Comment by Anrock** [comment]
Build instructions are working. But one have to read them :man_facepalming: 

Thanks to @befedo's instruction link I realized `qtmoc` isn't `moc` from Qt, it's a go wrapper around it.

It appears i've skimmed section about dependencies in the build instructions, because i thought it was macOS specific / about installing Qt itself or something. 
And then i've tried running `moc` from Qt instead of a go wrapper i should've installed :man_facepalming:

Everything works as expected.
Sorry for wasting your time.
