### ISSUE TITLE
File setting.toml missing at startup. GUI doesn't look like GUI in screenshots. 

### ISSUE THREAD

**Issue by Lisa-Williams** [akiyosi/gonvim#54]
Yesterday I installed [NeoVim from the Arch main repo](https://www.archlinux.org/packages/community/x86_64/neovim/). Followed by [GoNvim (fork) from the AUR](https://aur.archlinux.org/packages/gonvim-fork/).
I noticed two things.
- There is an error message when I start GoNvim: 
> [Gonvim] Error detected while parsing setting.toml: open /home/username/.gonvim

- The GUI doesn't even come close to the GUI visible in the screenshots on [the Wiki's Features page](https://github.com/akiyosi/gonvim/wiki/Features). Not even when I create a ```setting.toml``` file with the settings copy+pasted from [the Wiki's Configurations page](https://github.com/akiyosi/gonvim/wiki/Configurations#gonvim-config).

What went wrong?

![gonvim-startup-error-erased-username_20190506_233209](https://user-images.githubusercontent.com/6225311/57280674-871b2d80-70a9-11e9-88da-05eb8b4c63cf.png)

Edited to remove typos.

**Comment by Lisa-Williams** [comment]
Whatever!

**Comment by akiyosi** [comment]
Oh, sorry

> There is an error message when I start GoNvim:
>> [Gonvim] Error detected while parsing setting.toml: open /home/username/.gonvim

This is output when there is no `setting.toml`.
It is an unnecessary message, so it is not output at 0.4.0.

> The GUI doesn't even come close to the GUI visible in the screenshots on the Wiki's Features page. Not even when I create a setting.toml file with the settings copy+pasted from the Wiki's Configurations page.

Have you set up your neovim `init.vim`?
