### ISSUE TITLE
[Feature Request] Add support for GonvimFuzzy Resume

### ISSUE THREAD

**Issue by Mariappan** [akiyosi/gonvim#56]
Hi @akiyosi 

I was working on a feature to implement GonvimFuzzyResume to resume the previous search option using gonvim fuzzy. This will be useful in cases where you search for a text in a workspace and wanted to open the search results one by one. Otherwise you may need to move the cursor down again and again.

It's pretty much usable now.
Let me know if you are interested, will raise a pull request. 

Feel free to close this issue, if it sounds bloating

**Comment by akiyosi** [comment]
I am interested in that feature.
I want to try it.
I'm looking at your `multigrid_mine` branch, are there any fixes for your `gonvim-fuzzy` repo?

**Comment by Mariappan** [comment]
Yes I have not pushed. Will push now and let you know

**Comment by Mariappan** [comment]
Created the pull request in branch "feature-fuzzy-resume" in both gonvim and gonvim-fuzzy repositories.

Please check it out.
