### ISSUE TITLE
[Feature Request] Ligature support

### ISSUE THREAD

**Issue by Mariappan** [akiyosi/gonvim#63]
Not sure whether it is your roadmap
It would be very cool to support Ligatures in gonvim.

Feel free to close this issue if you feel its deviating your goal :)  
Like fira code :heart_eyes:

**Comment by akiyosi** [comment]
Hi😀
Do you want to display fonts like Fira Code, for example?

In fact, Gonvim supports ligatures in the previous 0.3.5.
Gonvim drastically changed the drawing method of characters in 0.4.0, but this change has eliminated ligature support. 

If you are not concerned about the drawing speed, you can draw ligatures by simply changing to the previous drawing method.

```
diff --git a/editor/font.go b/editor/font.go
index bb5582f..c83d826 100644
--- a/editor/font.go
+++ b/editor/font.go
@@ -71,7 +71,7 @@ func (f *Font) change(family string, size int) {
        f.shift = int(float64(f.lineSpace)/2 + ascent)

        // reset character cache
-       f.ws.screen.glyphMap = make(map[Cell]gui.QImage)
+       // f.ws.screen.glyphMap = make(map[Cell]gui.QImage)
 }

 func (f *Font) changeLineSpace(lineSpace int) {
diff --git a/editor/screen.go b/editor/screen.go
index 3a2b36c..8ffdc6b 100644
--- a/editor/screen.go
+++ b/editor/screen.go
@@ -360,7 +360,7 @@ func (w *Window) paint(event *gui.QPaintEvent) {

        p := gui.NewQPainter2(w.widget)

-       // p.SetFont(font.fontNew)
+       p.SetFont(font.fontNew)

        // Draw contents
        for y := row; y < row+rows; y++ {
@@ -368,8 +368,8 @@ func (w *Window) paint(event *gui.QPaintEvent) {
                        continue
                }
                w.fillBackground(p, y, col, cols)
-               w.drawChars(p, y, col, cols)
-               // w.drawText(p, y, col, cols)
+               // w.drawChars(p, y, col, cols)
+               w.drawText(p, y, col, cols)
                w.drawTextDecoration(p, y, col, cols)
        }
```

**Comment by akiyosi** [comment]
I add the `CachedDrawing` option in setting.toml with 367c3d8
With this change, `CachedDrawing` added in 0.4.0 has been made optional so you can use ligatures of Fira Code.

**Comment by smolck** [comment]
@akiyosi Would it be possible to add support for ligatures when using `CachedDrawing`, or is that not feasible?

**Comment by Mariappan** [comment]
> I added the `CachedDrawing` option in setting.toml with [367c3d8](https://github.com/akiyosi/gonvim/commit/367c3d8c607f6a8cb57aab53f00f2bc48157398c)
> With this change, `CachedDrawing` added in 0.4.0 has been made optional so you can use ligatures of Fira Code.

Wow. NThanks a lot :heart_eyes:

**Comment by akiyosi** [comment]
@smolck 
I think that it is possible to display ligatures by implementing a word-based cache instead of a character based it. 
The [newway-to-drawing-text-3](https://github.com/akiyosi/gonvim/tree/newway-to-drawing-text-3) is the branch that attempted word-based caching.

However, a size of word-based caches can grow indefinitely, so I think we need to implement a way to suppress this, such as LRU.
