### ISSUE TITLE
Remove “forked from dzhou121/gonvim” label

### ISSUE THREAD

**Issue by smolck** [akiyosi/gonvim#66]
Doing this (as I understand it) would help Gonvim in searches and such since it would no longer be a fork, but a standalone repo.

It is worth reading through this whole thread on the same topic for a different repo:
https://github.com/ctrlpvim/ctrlp.vim/issues/128

It provides this SO post, in which the accepted answer seems to indicate you can contact Github support and they can remove the “forked from” label:
https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

However, I think we should ask @dzhou121 if he is alright with this project no longer having the fork label (essentially becoming the main repo), as was done for ctrlp.vim:
https://github.com/ctrlpvim/ctrlp.vim/issues/128#issuecomment-153251330

@akiyosi What do you think?

**Comment by akiyosi** [comment]
Thank you for your opinions and information.

In my personal opinion, this fork has not yet reached the stage of taking a fork label.
I've added new API support and some experimental features in this fork, but I don't know if they are really good for the user.

According to the Github page below, the fork repository will be indexed if it exceeds the original number of stars. I thought this point was the time to consider taking a fork label.
https://help.github.com/en/github/searching-for-information-on-github/searching-in-forks

On the other hand, I am planning to rename the repository at the time of v0.4.0 release. The new name is goneovim.
If someone has a cooler name, they might consider hiring

**Comment by smolck** [comment]
> Thank you for your opinions and information.

No problem! Figured I’d suggest this since I didn’t know if you knew about it.

> In my personal opinion, this fork has not yet reached the stage of taking a fork label.
> I've added new API support and some experimental features in this fork, but I don't know if they are really good for the user.
> According to the Github page below, the fork repository will be indexed if it exceeds the original number of stars. I thought this point was the time to consider taking a fork label.
> https://help.github.com/en/github/searching-for-information-on-github/searching-in-forks

Good points. I just thought it might be a good idea since it appears dzhou121’s Gonvim repo has been abandoned, and this repo is (at least in my opinion) the maintained continuation of it. But I understand where you’re coming from ;)

> On the other hand, I am planning to rename the repository at the time of v0.4.0 release. The new name is goneovim.
> If someone has a cooler name, they might consider hiring

I’m curious, why the name change?

**Comment by akiyosi** [comment]
> I’m curious, why the name change?

The reason is that this repository implements some experimental additional features and will be transformed into different applications from the original.

**Comment by smolck** [comment]
Hey @akiyosi, it appears I can't search around the code in this repository from GitHub because it's a fork. GitHub just says `Sorry, forked repositories are not currently searchable.`. Just wanted to let you know since it makes it a bit more difficult to search for code around the repository.
