### ISSUE TITLE
gonvim not working in MacOS Mojave

### ISSUE THREAD

**Issue by akiyosi** [akiyosi/gonvim#8]
gonvim.app not working in MacOS Mojave.
But, it works via command line;

```
/Applications/gonvim.app/Contents/MacOS/gonvim
```

**Comment by bfulop** [comment]
I have a similar issue:

I am able to launch gonvim from the app icon, but it seems like it just creates an empty window. 
This what I get when clicking on _"Show all windows"_ in the dock. The clicks do seem to be captured by Gonvim (doesn't click through the empty window).  

The nvim executable is correctly symlinked to `/usr/local/bin/nvim`.

This is on Mojave (just using the old desktop image).

![gonvim_windows](https://user-images.githubusercontent.com/1718128/48010303-9848a900-e11d-11e8-8709-e8e9faf503ca.jpg)

**Comment by bfulop** [comment]
I just updated to the latest version of Neovim (`3.2`) and gonvim now working perfectly on my machine (Mojave)! Can just launch via Spotlight and it starts up normally.

**Comment by akiyosi** [comment]
HI,
Thanks for the report🙂

But in my mojave environment, I can not start gonvim...
Do you have any additional settings? (For example security)

**Comment by bfulop** [comment]
Yes, I did allow the launching of Gonvim in the _Security & Privacy_ system preferences panel.

I also did:

```
$ brew uninstall neovim
```

then

```
$ brew install --HEAD neovim
```

to get the latest version of Neovim and after that it just worked™️.

By the way, I did a clean install of Mojave so no cruft left over from before...

**Comment by smolck** [comment]
@akiyosi Are you still having problems opening Gonvim in Mojave? I would like to try and help out with a fix if this is still a problem (although I don’t use Mac OS so I’m not sure if I can).

**Comment by akiyosi** [comment]
@smolck 
Hi😀
There is no problem in my MacOS Mojave environment I am currently using.
The Mojave environment I had a problem with is a virtual machine on MacOS High Sierra. 
I think the VM environment is probably the cause of the problem, but I don't know now.

**Comment by smolck** [comment]
Hello, thanks for the response! So, does that mean this issue can be closed now?

**Comment by akiyosi** [comment]
@smolck 
I thought that there was a similar problem in your environment that you cared about this problem.
If there is no problem, I will close it.

**Comment by smolck** [comment]
> I thought that there was a similar problem in your environment that you cared about this problem.

Thankfully no, I have no problems like this (I don't use Mac OS). Forgive me for the misunderstanding.

> If there is no problem, I will close it.

Sounds good!
